version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      timezone: UTC
      time: "07:00"
    open-pull-requests-limit: 50
    ignore:
      # These are required by docusaurus
      - dependency-name: "react"
      - dependency-name: "react-dom"
